// Generated by CoffeeScript 1.4.0
(function() {

  exports.index = function(req, res) {
    var testjson;
    res.contentType('application/json');
    testjson = {
      name: "aaa",
      content: "asdas",
      position: {
        x: 123,
        y: 234
      }
    };
    return res.send(testjson);
  };

}).call(this);
