// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    return $.getJSON("http://localhost:3000/getall.json", function(jsonarr) {
      var json, _i, _len;

      for (_i = 0, _len = jsonarr.length; _i < _len; _i++) {
        json = jsonarr[_i];
        $("body").append("<div><a href='" + json.url + "'>" + json.url + "</a>:" + json.content + "</div>");
      }
      return $("a").click(function(e) {
        console.log(e.target);
        return chrome.tabs.create({
          "url": "" + e.target.href,
          "selected": true
        });
      });
    });
  });

}).call(this);
